### ISSUE TITLE
Vastloadtimeout not work

### ISSUE THREAD

**Issue by KVA24** [kslimani/ima-ad-player#36]
I test this with case vast loadtimeout but it not fire the error, can you check it

**Comment by kslimani** [comment]
Hello, can you please give me more information about your issue ?

Are you talking about `vastLoadTimeout` in `adsRequestOptions` ?

**Comment by KVA24** [comment]
Yep, I use your config example, and set time for _vastLoadTimeout_ in _adsRequestOptions_, then I try with low internet connect, ImaAdPlayer only fire ad_request then ad_end after timeout, not an ad_error I want

**Comment by KVA24** [comment]
Yep, I use your config example, and set time for *vastLoadTimeout* in
*adsRequestOptions*, then I try with low internet connect, ImaAdPlayer only
fire ad_request then ad_end after timeout, not an ad_error I want

Vào Th 5, 23 thg 11, 2023 vào lúc 02:21 kslimani ***@***.***>
đã viết:

**Comment by kslimani** [comment]
i have done some tests and it work as expected for me :

```js
// [...]
ImaAdPlayer({
  // [...]
  adsRequestOptions: {
    vastLoadTimeout: 10000, // Set VAST XML load timeout to ten seconds
  },
}, function(player, error) {
  // [...]
  player.on('ad_error', function(o) {
    // Should be dispatched on XML VAST load timeout (ie: response took more than 10 seconds)
  });
});
```

Please note this timeout apply ONLY to the HTTP request which attempt to load the VAST XML ad response. It does NOT affect the video ad playback part. (refer to IMA documentation for more details)

**Comment by KVA24** [comment]
I do a retest and it work perfectly now, many thanks for your help <3

Vào Th 7, 25 thg 11, 2023 vào lúc 17:09 kslimani ***@***.***>
đã viết:
