### ISSUE TITLE
Pause ads problem

### ISSUE THREAD

**Issue by KVA24** [kslimani/ima-ad-player#37]
Sorry to bother you,
I want to ask about a problem, when the ad starts, I can stop it by clicking. But I don't want that, so is there a way to stop this action?
I tried resume the player after "ad_pause" event, but this will cause a delay in the experience.

**Comment by kslimani** [comment]
By default, ad click is handled by the IMA ad itself. (default behaviour may differ if ad is played, for example, using VPAID)

A solution is to implement custom ad click element, using the [clickTrackingElement](https://github.com/kslimani/ima-ad-player/blob/master/docs/config.md) option.

see also [AdDisplayContainer](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/ima.AdDisplayContainer#AdDisplayContainer) `opt_clickTrackingElement` argument from IMA documentation.

**Comment by KVA24** [comment]
I tried your option of using clickTrackingElement, but it didn't work.
Another problem, when I tested it on some Mac devices using the Safari browser, there was a phenomenon of black screen ads when pausing. Do you have experience with this issue?

**Comment by kslimani** [comment]
Nothing comes to my mind about this black screen ads.
