### ISSUE TITLE
Memories problem

### ISSUE THREAD

**Issue by KVA24** [kslimani/ima-ad-player#46]
Dear kslimani, 
I still working with your repo, then I have an issue about memories, when I try to init ad multiple time, in one video player, memories keep rise up even when I using player.destroy() before init new ad. Please give me some advice, thank you so much.

**Comment by kslimani** [comment]
Hello @KVA24 ,

In JavaScript, a common way to ensure memory is released is to assign null to object reference.

For exemple :

```js
let playerInstance;  // Let's assume it contains player instance.

// When you are done you call destroy method then set variable to null
playerInstance.destroy();
playerInstance = null;
```

**Comment by KVA24** [comment]
Dear @kslimani ,
I used your solution, the memory has decreased but not significantly, the increase is still very clear every time I transfer video content and init a new ad. Is there anything else to pay attention to?

You can see it in my sample: https://wiinvent.tv/pub-test.html

Try repeat switch between two video, then you will see the memory raise up

**Comment by kslimani** [comment]
In your sample page, it seems you are using videojs player.

I recommend to take a look at this projet : https://github.com/videojs/videojs-contrib-ads

Another way (much easier i think) could be to use IMA plugin for videojs : https://github.com/googleads/videojs-ima

**Comment by KVA24** [comment]
I also using shaka js and hls player as well, tks for your recommendation but could this problem about memory be fix ?

**Comment by kslimani** [comment]
I released a new version with enhanced destroy method, hope it helps to solve your issue.

On the contrary, the memory leak probably doesn't come from this library. (unless i missed something obvious)

**Comment by KVA24** [comment]
I noticed this problem happens in both the ima-sdk and videojs-ima sample, hopefully it will be fixed soon. Thank you for your enthusiastic support

**Comment by KVA24** [comment]
Thank you very much for your enthusiastic support.
