### ISSUE TITLE
Locale is not working

### ISSUE THREAD

**Issue by lanceloti** [kslimani/ima-ad-player#5]
Locale is never define on configure method.

**Comment by kslimani** [comment]
@lanceloti by default, [locale](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/ima.ImaSdkSettings#setLocale) is not set if option is not provided in constructor _(i think default value is 'en' in IMA SDK)_.

If you want to setup locale, add the `locale` parameter with [locale code](https://developers.google.com/interactive-media-ads/docs/sdks/html5/localization) in the configuration object :

```javascript
var videoElement = document.querySelector('.a-video-element');
var adContainer = document.querySelector('.a-display-container-element');

ImaAdPlayer({
  video: videoElement,
  displayContainer: adContainer,
  tag: 'https://myadserver.com/path/to/vast/tag.xml',
  locale: 'fr',
}, function(player, error) {
  // [...]
});
```

**Comment by kslimani** [comment]
@lanceloti nevermind, i think you are right, i checked source code and i may have forgot something.

I will take a deeper look ASAP.

Thank you for reporting the issue !

**Comment by kslimani** [comment]
@lanceloti i released a new version which should fix the issue.
